# This file sets some good defaults for the local development of a platform.sh
# laravel project using lando
#
# Note that you should not edit this file so it can continue to receive upstream
# updates. If you wish to change the values you simply override them in your
# normal .lando.yml

config:
  # Generally this section overrides production variables and settings for
  # values that make more sense for local development
  # Note that "app" is the name of one of your platform applications
  # Note that the syntax under each app is the same as the format defined here
  # https://docs.platform.sh/configuration/app/variables.html
  variables:
    app:
      env:
        APP_ENV: development
        APP_DEBUG: 1


# These are Laravel specific tools that are commonly used during development
tooling:
  artisan:
    cmd: /app/artisan
    service: app

